SANDBOX_SITE=https://centinelapistag.cardinalcommerce.com/
PROD_SITE=https://centinelapi.cardinalcommerce.com/
FIDO_INIT=V2/FIDO/Init
FIDO_CHALLENGE=V2/FIDO/Challenge
JWT_API_KEY_ID=67288b1450228171efd237da
JWT_ORG_UNIT_ID=67288b135b031c441a5b80ca
JWT_SECRET=3cd432ad-6374-4b79-bd8b-170dc8646c6f
MERCHANT_ORIGIN=https://demo.sean.io
RETURN_URL=https://demo.sean.io
